### ISSUE TITLE
(Permission denied) on X server ":10.0 

### ISSUE THREAD

**Issue by prabanjanGITHUB** [Robotics010/carla_autoware_bridge#17]
pp@pp-Virtual-Machine:~/CARLA_0.9.12$ ./CarlaUE4.sh 
4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps.
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
XIO:  fatal IO error 13 (Permission denied) on X server ":10.0"
      after 285 requests (285 known processed) with 107 events remaining.
terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Signal 6 caught.
Segmentation fault (core dumped)

when launching carla, I am facing this issue. I am running my VM in hyper v. Any help here?

**Comment by Robotics010** [comment]
Hey @prabanjanGITHUB, unfortunately it is connected with CARLA simulator only and not with `carla_autoware_bridge`, so my help here is constrained. I would suggest you find help with CARLA [docs and resourses](https://carla.readthedocs.io/en/latest/cont_contribution_guidelines/#report-bugs).

As far as I understand you are trying to launch CARLA linux build inside windows' hyper.v, windows virtualization tool. Running CARLA inside a VM can be tricky, since CARLA requires high performance graphics and desktop VM solutions often abstract the graphics hardware with intermediary driver layers.

I would suggest to use CARLA natively without a virtual machine because looking for ways to allow the VM to have direct access to the host GPU could take more time instead of installing Linux and launching CARLA directly.
